In [1]:
import pandas as pd

In [8]:
import csv

with open("RNN_dataset.csv", "r", encoding="utf-8", errors="replace", newline="") as f:
    for i, line in enumerate(f, start=1):
        if 18 <= i <= 24:
            print(f"Line {i}: {line[:500]!r}")

Line 18: '"Some films just simply should not be remade. This is one of them. In and of itself it is not a bad film. But it fails to capture the flavor and the terror of the 1963 film of the same title. Liam Neeson was excellent as he always is, and most of the cast holds up, with the exception of Owen Wilson, who just did not bring the right feel to the character of Luke. But the major fault with this version is that it strayed too far from the Shirley Jackson story in it\'s attempts to be grandiose and lo'
Line 19: '"This movie made it into one of my top 10 most awful movies. Horrible. <br /><br />There wasn\'t a continuous minute where there wasn\'t a fight with one monster or another. There was no chance for any character development, they were too busy running from one sword fight to another. I had no emotional attachment (except to the big bad machine that wanted to destroy them) <br /><br />Scenes were blatantly stolen from other movies, LOTR, Star Wars and Matrix. <br /><br />Examples<br /><br />>The gh'
Line 20: '"I remember this film,it was the first film i had watched at the cinema the picture was dark in places i was very nervous it was back in 74/75 my Dad took me my brother & sister to Newbury cinema in Newbury Berkshire England. I recall the tigers and the lots of snow in the film also the appearance of Grizzly Adams actor Dan Haggery i think one of the tigers gets shot and dies. If anyone knows where to find this on DVD etc please let me know.The cinema now has been turned in a fitness club which '
Line 21: '"An awful film! It must have been up against some real stinkers to be nominated for the Golden Globe. They\'ve taken the story of the first famous female Renaissance painter and mangled it beyond recognition. My complaint is not that they\'ve taken liberties with the facts; if the story were good, that would perfectly fine. But it\'s simply bizarre -- by all accounts the true story of this artist would have made for a far better film, so why did they come up with this dishwater-dull script? I suppo'
Line 22: '"After the success of Die Hard and it\'s sequels it\'s no surprise really that in the 1990s, a glut of \'Die Hard on a .....\' movies cashed in on the wrong guy, wrong place, wrong time concept. That is what they did with Cliffhanger, Die Hard on a mountain just in time to rescue Sly \'Stop or My Mom Will Shoot\' Stallone\'s career.<br /><br />Cliffhanger is one big nit-pickers dream, especially to those who are expert at mountain climbing, base-jumping, aviation, facial expressions, acting skills. All'
Line 23: '"I had the terrible misfortune of having to view this ""b-movie"" in it\'s entirety.<br /><br />All I have to say is--- save your time and money!!! This has got to be the worst b-movie of all time, it shouldn\'t even be called a b-movie, more like an f-movie! Because it fails in all aspects that make a good movie: the story is not interesting at all, all of the actors are paper-thin and not at all believable, it has bad direction and the action sequences are so fake it\'s almost funny.......almost.'
Line 24: '"What an absolutely stunning movie, if you have 2.5 hrs to kill, watch it, you won\'t regret it, it\'s too much fun! Rajnikanth carries the movie on his shoulders and although there isn\'t anything more other than him, I still liked it. The music by A.R.Rehman takes time to grow on you but after you heard it a few times, you really start liking it.",positive\n'

In [14]:
import pandas as pd
import csv

df = pd.read_csv(
    "RNN_dataset.csv",
    engine="python",
    quoting=csv.QUOTE_MINIMAL,
    on_bad_lines="skip"
)

print("Shape:", dataset.shape)
print(dataset.columns.tolist())
display(dataset.head())

Shape: (6746, 2)
['review', 'sentiment']

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [10]:
dataset.shape

(6746, 2)

In [12]:
dataset.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [16]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

# preprocessing

In [18]:
df["review"] = df["review"].str.lower()

In [19]:
import re

# sample_text = "abc is the word, abc" # abc => xyz

# new_text = re.sub("abc", "xyz", sample_text)

In [20]:
def remove_urls(text):
    text = re.sub(r"http\S+" , "", text)  # (pattern, repl, string) eg - https://www.google.com
    return text
    
df["review"] = df["review"].apply(remove_urls)

In [21]:
def remove_punctuations(text):
    text = re.sub(r"[^A-Za-z0-9\s]" , "", text) # A-Z a-z 0-9 \s
    return text

df["review"] = df["review"].apply(remove_punctuations)

In [22]:
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production br br the filmin...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically theres a family where a little boy j...  negative
4  petter matteis love in the time of money is a ...  positive

In [23]:
def remove_html(text):
    text = re.sub(r"<.*?>" , "", text)
    return text

df["review"] = df["review"].apply(remove_html)

In [26]:
import nltk

nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /Users/akhil/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /Users/akhil/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[nltk_data] Downloading package stopwords to /Users/akhil/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [27]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

sample_text = "I like coding in python"

tokens = word_tokenize(sample_text)

stop_words = set(stopwords.words('english'))

In [29]:
def remove_stopwords(text):
    tokens = word_tokenize(text)
    stop_words = stopwords.words("english")

    for word in tokens:
        if word in stop_words:
            text = text.replace(word, "")

    return text

df["review"] = df["review"].apply(remove_stopwords)

In [31]:
# running -> run
# played -> play
# PorterStemming

from nltk.stem import PorterStemmer

In [32]:
def stemming(text):
    ps = PorterStemmer()
    stemmed_words = []

    tokens = word_tokenize(text)
    for token in tokens:
        stemmed_token = ps.stem(token)
        stemmed_words.append(stemmed_token)

    return " ".join(stemmed_words)

df["review"] = df["review"].apply(stemming)

In [33]:
df.head()

                                              review sentiment
0  e revew nted wtchg 1 oz epod ll hook y rght ex...  positive
1  wder ltle producti br br film techniqu unssum ...  positive
2  thought th wder wy spend tme o hot summer week...  positive
3  bsclli re fmli lttle boy jke thk re zomb close...  negative
4  petter mtte love time mey vulli stunng film wt...  positive

# ENCODING

In [34]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df["sentiment"] = le.fit_transform(df["sentiment"])

In [35]:

y = df["sentiment"]

# VECTORIZATION

In [36]:
from sklearn.feature_extraction.text import TfidfVectorizer

tf = TfidfVectorizer(max_features=5000)

X = tf.fit_transform(df["review"])

In [37]:
X

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 556393 stored elements and shape (6746, 5000)>

# dataloader adn dataset

In [38]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [39]:
import torch
from torch.utils.data import TensorDataset, DataLoader

In [40]:
X_train = X_train.toarray()
X_test = X_test.toarray()

In [42]:
train_set = TensorDataset(
    torch.from_numpy(X_train.copy()).float(),
    torch.from_numpy(y_train.to_numpy().copy()).float()
)

test_set = TensorDataset(
    torch.from_numpy(X_test.copy()).float(),
    torch.from_numpy(y_test.to_numpy().copy()).float()
)

In [43]:
train_loader = DataLoader(train_set, shuffle=True, batch_size=64)
test_loader = DataLoader(test_set, shuffle=True, batch_size=64)

# building model

In [44]:
import torch.nn as nn
import torch.optim as optim

In [45]:
class RNN(nn.Module):
    def __init__(self, input_size, hidden_size=128, num_layers=1):
        super().__init__()

        self.hidden_size = hidden_size
        self.num_layers = num_layers

        # RNN layer
        self.rnn = nn.RNN(input_size, hidden_size, num_layers, batch_first=True)

        # fully connected layer
        self.fc = nn.Linear(hidden_size, 1)

    def forward(self, x):
        # optional => shape (num of layers, batch size, hidden size)
        h0 = torch.zeros(self.num_layers, x.size(0), self.hidden_size)

        out, _ = self.rnn(x, h0) 
        # 1st value = hidden state of all the timesteps => (batch, seq_len, hidden size)
        # 2nd value = final hidden state of last timestep

        out = self.fc(out[:, -1, :])
        return out

In [46]:
input_size = X_train.shape[1]

model = RNN(input_size)

criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters())

# training RNN

In [47]:
epochs = 10

for epoch in range(epochs):
    model.train()

    for Xb, yb in train_loader:
        optimizer.zero_grad()

        Xb = Xb.unsqueeze(1) # add singleton direction
        
        outputs = model(Xb) # (batch_size, 1)

        outputs = torch.sigmoid(outputs.squeeze()) # (batch_size,) => probability

        loss = criterion(outputs, yb) # compute loss
        loss.backward() # backprop
        optimizer.step() # weights update

    print(f"epoch = {epoch+1}/{epochs} and loss = {loss.item()}")

epoch = 1/10 and loss = 0.5312570929527283
epoch = 2/10 and loss = 0.22289970517158508
epoch = 3/10 and loss = 0.27153846621513367
epoch = 4/10 and loss = 0.17069177329540253
epoch = 5/10 and loss = 0.17635302245616913
epoch = 6/10 and loss = 0.11540082842111588
epoch = 7/10 and loss = 0.15114501118659973
epoch = 8/10 and loss = 0.07407175004482269
epoch = 9/10 and loss = 0.035605259239673615
epoch = 10/10 and loss = 0.02408675290644169

In [48]:
# evaluate

model.eval()

with torch.no_grad():
    correct_vals = 0
    tot_vals = 0
    
    for Xb, yb in test_loader:
        Xb = Xb.unsqueeze(1)

        outputs = model(Xb)
        predicted = (torch.sigmoid(outputs.squeeze()) > 0.5).float()

        tot_vals += yb.size(0)
        correct_vals += (predicted == yb).sum().item()

    print(f"accuracy = {correct_vals/tot_vals*100}")

accuracy = 83.55555555555556