In [33]:
import pandas as pd

In [105]:
dataset=pd.read_csv("loan.csv")
dataset
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 20 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Applicant_ID        950 non-null    float64
 1   Applicant_Income    950 non-null    float64
 2   Coapplicant_Income  950 non-null    float64
 3   Employment_Status   950 non-null    str
 4   Age                 950 non-null    float64
 5   Marital_Status      950 non-null    str
 6   Dependents          950 non-null    float64
 7   Credit_Score        950 non-null    float64
 8   Existing_Loans      950 non-null    float64
 9   DTI_Ratio           950 non-null    float64
 10  Savings             950 non-null    float64
 11  Collateral_Value    950 non-null    float64
 12  Loan_Amount         950 non-null    float64
 13  Loan_Term           950 non-null    float64
 14  Loan_Purpose        950 non-null    str
 15  Property_Area       950 non-null    str
 16  Education_Level     950 non-null    str
 17  Gender              950 non-null    str
 18  Employer_Category   950 non-null    str
 19  Loan_Approved       950 non-null    str
dtypes: float64(12), str(8)
memory usage: 156.4 KB

## HANDLING MISSING VALUES

In [106]:
from sklearn.impute import SimpleImputer

In [107]:
categorical_columns=dataset.select_dtypes(include=["str"]).columns
numerical_columns=dataset.select_dtypes(include=["float64"]).columns
categorical_columns

Index(['Employment_Status', 'Marital_Status', 'Loan_Purpose', 'Property_Area',
       'Education_Level', 'Gender', 'Employer_Category', 'Loan_Approved'],
      dtype='str')

In [108]:
num_imp=SimpleImputer(strategy="mean")
dataset[numerical_columns]=num_imp.fit_transform(dataset[numerical_columns]);

cat_imp=SimpleImputer(strategy="most_frequent")
dataset[categorical_columns]=cat_imp.fit_transform(dataset[categorical_columns]);

dataset

,Applicant_ID,Applicant_Income,Coapplicant_Income,Employment_Status,Age,Marital_Status,Dependents,Credit_Score,Existing_Loans,DTI_Ratio,Savings,Collateral_Value,Loan_Amount,Loan_Term,Loan_Purpose,Property_Area,Education_Level,Gender,Employer_Category,Loan_Approved
0,1.0,17795.000000,1387.0,Salaried,51.0,Married,0.0,637.0,4.0,0.53,19403.000000,45638.0,16619.0,84.0,Personal,Urban,Not Graduate,Female,Private,No
1,2.0,2860.000000,2679.0,Salaried,46.0,Married,3.0,621.0,2.0,0.30,2580.000000,49272.0,38687.0,48.0,Car,Semiurban,Graduate,Male,Private,No
2,3.0,7390.000000,2106.0,Salaried,25.0,Single,2.0,674.0,4.0,0.20,13844.000000,6908.0,27943.0,72.0,Business,Urban,Graduate,Female,Government,Yes
3,4.0,13964.000000,8173.0,Salaried,40.0,Married,2.0,579.0,3.0,0.31,9553.000000,10844.0,27819.0,60.0,Business,Rural,Graduate,Female,Government,No
4,5.0,13284.000000,4223.0,Self-employed,31.0,Single,2.0,721.0,1.0,0.29,9386.000000,37629.0,12741.0,72.0,Car,Urban,Graduate,Male,Private,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996.0,10852.571579,9092.0,Salaried,58.0,Married,0.0,557.0,0.0,0.59,5370.000000,43563.0,8311.0,72.0,Personal,Urban,Not Graduate,Male,Unemployed,No
996,997.0,3279.000000,6356.0,Self-employed,58.0,Married,1.0,646.0,3.0,0.19,9940.452632,18361.0,22563.0,12.0,Business,Urban,Graduate,Female,Government,No
997,998.0,15192.000000,8433.0,Contract,48.0,Single,1.0,666.0,1.0,0.40,8581.000000,41335.0,16203.0,24.0,Home,Rural,Graduate,Male,MNC,No
998,999.0,9083.000000,7380.0,Unemployed,50.0,Single,1.0,748.0,3.0,0.31,13491.000000,8933.0,10290.0,36.0,Personal,Urban,Graduate,Male,Private,Yes
999,1000.0,13093.000000,2385.0,Salaried,23.0,Married,1.0,613.0,3.0,0.32,12436.000000,25816.0,35818.0,48.0,Personal,Semiurban,Graduate,Male,Private,No

In [109]:
dataset=dataset.drop("Applicant_ID",axis=1)

# feature encoding

In [110]:
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Applicant_Income    1000 non-null   float64
 1   Coapplicant_Income  1000 non-null   float64
 2   Employment_Status   1000 non-null   str
 3   Age                 1000 non-null   float64
 4   Marital_Status      1000 non-null   str
 5   Dependents          1000 non-null   float64
 6   Credit_Score        1000 non-null   float64
 7   Existing_Loans      1000 non-null   float64
 8   DTI_Ratio           1000 non-null   float64
 9   Savings             1000 non-null   float64
 10  Collateral_Value    1000 non-null   float64
 11  Loan_Amount         1000 non-null   float64
 12  Loan_Term           1000 non-null   float64
 13  Loan_Purpose        1000 non-null   str
 14  Property_Area       1000 non-null   str
 15  Education_Level     1000 non-null   str
 16  Gender              1000 non-null   str
 17  Employer_Category   1000 non-null   str
 18  Loan_Approved       1000 non-null   str
dtypes: float64(11), str(8)
memory usage: 148.6 KB

In [111]:
from sklearn.preprocessing import OneHotEncoder,LabelEncoder

In [112]:
categorical_columns=dataset.select_dtypes(include=["str"]).columns
categorical_columns

Index(['Employment_Status', 'Marital_Status', 'Loan_Purpose', 'Property_Area',
       'Education_Level', 'Gender', 'Employer_Category', 'Loan_Approved'],
      dtype='str')

In [113]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
import pandas as pd

# Columns for One-Hot Encoding
columns_OneHot = [
    "Employment_Status",
    "Property_Area",
    "Gender",
    "Employer_Category",
    "Loan_Approved",
    "Marital_Status"
]

# Label Encoder
LE = LabelEncoder()

dataset["Education_Level"] = LE.fit_transform(dataset["Education_Level"])
dataset["Loan_Purpose"] = LE.fit_transform(dataset["Loan_Purpose"])

# One-Hot Encoder
OE = OneHotEncoder(
    drop="first",
    sparse_output=False,
    handle_unknown="ignore"
)

# Transform the selected columns
encoded_array = OE.fit_transform(dataset[columns_OneHot])

# Create DataFrame of encoded columns
encoded_dataset = pd.DataFrame(
    encoded_array,
    columns=OE.get_feature_names_out(columns_OneHot),
    index=dataset.index
)

# Drop original columns and concatenate encoded columns
dataset = pd.concat(
    [dataset.drop(columns=columns_OneHot), encoded_dataset],
    axis=1
)

# Display first few rows
dataset.head()

,Applicant_Income,Coapplicant_Income,Age,Dependents,Credit_Score,Existing_Loans,DTI_Ratio,Savings,Collateral_Value,Loan_Amount,...,Employment_Status_Unemployed,Property_Area_Semiurban,Property_Area_Urban,Gender_Male,Employer_Category_Government,Employer_Category_MNC,Employer_Category_Private,Employer_Category_Unemployed,Loan_Approved_Yes,Marital_Status_Single
0,17795.0,1387.0,51.0,0.0,637.0,4.0,0.53,19403.0,45638.0,16619.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,2860.0,2679.0,46.0,3.0,621.0,2.0,0.30,2580.0,49272.0,38687.0,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
2,7390.0,2106.0,25.0,2.0,674.0,4.0,0.20,13844.0,6908.0,27943.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0
3,13964.0,8173.0,40.0,2.0,579.0,3.0,0.31,9553.0,10844.0,27819.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,13284.0,4223.0,31.0,2.0,721.0,1.0,0.29,9386.0,37629.0,12741.0,...,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0

In [114]:
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 25 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Applicant_Income                 1000 non-null   float64
 1   Coapplicant_Income               1000 non-null   float64
 2   Age                              1000 non-null   float64
 3   Dependents                       1000 non-null   float64
 4   Credit_Score                     1000 non-null   float64
 5   Existing_Loans                   1000 non-null   float64
 6   DTI_Ratio                        1000 non-null   float64
 7   Savings                          1000 non-null   float64
 8   Collateral_Value                 1000 non-null   float64
 9   Loan_Amount                      1000 non-null   float64
 10  Loan_Term                        1000 non-null   float64
 11  Loan_Purpose                     1000 non-null   int64
 12  Education_Level                  1000 non-null   int64
 13  Employment_Status_Salaried       1000 non-null   float64
 14  Employment_Status_Self-employed  1000 non-null   float64
 15  Employment_Status_Unemployed     1000 non-null   float64
 16  Property_Area_Semiurban          1000 non-null   float64
 17  Property_Area_Urban              1000 non-null   float64
 18  Gender_Male                      1000 non-null   float64
 19  Employer_Category_Government     1000 non-null   float64
 20  Employer_Category_MNC            1000 non-null   float64
 21  Employer_Category_Private        1000 non-null   float64
 22  Employer_Category_Unemployed     1000 non-null   float64
 23  Loan_Approved_Yes                1000 non-null   float64
 24  Marital_Status_Single            1000 non-null   float64
dtypes: float64(23), int64(2)
memory usage: 195.4 KB

## Corelation Matric

In [115]:
nums_columns=dataset.select_dtypes(include="number");
correleation_mat=nums_columns.corr()["Loan_Approved_Yes"].sort_values(ascending=False)
correleation_mat

Loan_Approved_Yes                  1.000000
Credit_Score                       0.451175
Applicant_Income                   0.119796
Employer_Category_MNC              0.069049
Marital_Status_Single              0.030182
Property_Area_Urban                0.025963
Collateral_Value                   0.021868
Loan_Purpose                       0.013305
Coapplicant_Income                 0.004230
Employment_Status_Self-employed   -0.001337
Employer_Category_Private         -0.003347
Property_Area_Semiurban           -0.012967
Savings                           -0.013437
Employer_Category_Unemployed      -0.021468
Age                               -0.022343
Dependents                        -0.023811
Existing_Loans                    -0.034794
Employer_Category_Government      -0.039187
Employment_Status_Salaried        -0.041428
Employment_Status_Unemployed      -0.044464
Education_Level                   -0.052920
Gender_Male                       -0.054342
Loan_Term                         -0.086644
Loan_Amount                       -0.126499
DTI_Ratio                         -0.444783
Name: Loan_Approved_Yes, dtype: float64

## test train and split

In [116]:
X=dataset.drop(columns=["Loan_Approved_Yes"])
Y=dataset["Loan_Approved_Yes"]
X

,Applicant_Income,Coapplicant_Income,Age,Dependents,Credit_Score,Existing_Loans,DTI_Ratio,Savings,Collateral_Value,Loan_Amount,...,Employment_Status_Self-employed,Employment_Status_Unemployed,Property_Area_Semiurban,Property_Area_Urban,Gender_Male,Employer_Category_Government,Employer_Category_MNC,Employer_Category_Private,Employer_Category_Unemployed,Marital_Status_Single
0,17795.000000,1387.0,51.0,0.0,637.0,4.0,0.53,19403.000000,45638.0,16619.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
1,2860.000000,2679.0,46.0,3.0,621.0,2.0,0.30,2580.000000,49272.0,38687.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
2,7390.000000,2106.0,25.0,2.0,674.0,4.0,0.20,13844.000000,6908.0,27943.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
3,13964.000000,8173.0,40.0,2.0,579.0,3.0,0.31,9553.000000,10844.0,27819.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,13284.000000,4223.0,31.0,2.0,721.0,1.0,0.29,9386.000000,37629.0,12741.0,...,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,10852.571579,9092.0,58.0,0.0,557.0,0.0,0.59,5370.000000,43563.0,8311.0,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
996,3279.000000,6356.0,58.0,1.0,646.0,3.0,0.19,9940.452632,18361.0,22563.0,...,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
997,15192.000000,8433.0,48.0,1.0,666.0,1.0,0.40,8581.000000,41335.0,16203.0,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0
998,9083.000000,7380.0,50.0,1.0,748.0,3.0,0.31,13491.000000,8933.0,10290.0,...,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0
999,13093.000000,2385.0,23.0,1.0,613.0,3.0,0.32,12436.000000,25816.0,35818.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0

In [117]:
Y

0      0.0
1      0.0
2      1.0
3      0.0
4      1.0
      ...
995    0.0
996    0.0
997    0.0
998    1.0
999    0.0
Name: Loan_Approved_Yes, Length: 1000, dtype: float64

In [118]:
from sklearn.model_selection import train_test_split

In [119]:
X_train,X_test,Y_train,Y_test=train_test_split(
    X,Y,test_size=0.2,random_state=42
)

In [120]:
from sklearn.preprocessing import StandardScaler

In [121]:
scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)

## training and evaluating about model

In [145]:
 #logistic regression 
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,precision_score,recall_score,confusion_matrix
model1=LogisticRegression(max_iter=5000)

model1.fit(X_train_scaled,Y_train)

Y_predict=model1.predict(X_test_scaled)

print("accuracy-",accuracy_score(Y_test,Y_predict))
print("recall-",recall_score(Y_test,Y_predict))
print("precison-",precision_score(Y_test,Y_predict))
print(confusion_matrix(Y_test,Y_predict))

accuracy- 0.86
recall- 0.7540983606557377
precison- 0.7796610169491526
[[126  13]
 [ 15  46]]

In [146]:
#KNN
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score,precision_score,recall_score,confusion_matrix
model2=KNeighborsClassifier(n_neighbors=5)

model2.fit(X_train_scaled,Y_train)

Y_predict=model2.predict(X_test_scaled)

print("accuracy-",accuracy_score(Y_test,Y_predict))
print("recall-",recall_score(Y_test,Y_predict))
print("precison-",precision_score(Y_test,Y_predict))
print(confusion_matrix(Y_test,Y_predict))

accuracy- 0.77
recall- 0.4918032786885246
precison- 0.6666666666666666
[[124  15]
 [ 31  30]]

In [147]:
#naive_bayes
#KNN
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score,precision_score,recall_score,confusion_matrix
model3=GaussianNB()
model3.fit(X_train_scaled,Y_train)

Y_predict=model3.predict(X_test_scaled)

print("accuracy-",accuracy_score(Y_test,Y_predict))
print("recall-",recall_score(Y_test,Y_predict))
print("precison-",precision_score(Y_test,Y_predict))
print(confusion_matrix(Y_test,Y_predict))

accuracy- 0.865
recall- 0.7540983606557377
precison- 0.7931034482758621
[[127  12]
 [ 15  46]]

## imporroving mode

In [137]:
import numpy as np
dataset["sredit_new"]=dataset["Credit_Score"] ** 2
dataset["new_DTI_Ratio"]=dataset["DTI_Ratio"] **2


X=dataset.drop(columns=["Loan_Approved_Yes","Credit_Score","DTI_Ratio"])
Y=dataset["Loan_Approved_Yes"]
X

,Applicant_Income,Coapplicant_Income,Age,Dependents,Existing_Loans,Savings,Collateral_Value,Loan_Amount,Loan_Term,Loan_Purpose,...,Property_Area_Urban,Gender_Male,Employer_Category_Government,Employer_Category_MNC,Employer_Category_Private,Employer_Category_Unemployed,Marital_Status_Single,sredit_new,new_DTI_Ratio,new_Applicant_Income
0,17795.000000,1387.0,51.0,0.0,4.0,19403.000000,45638.0,16619.0,84.0,4,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,405769.0,0.2809,9.786729
1,2860.000000,2679.0,46.0,3.0,2.0,2580.000000,49272.0,38687.0,48.0,1,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,385641.0,0.0900,7.958926
2,7390.000000,2106.0,25.0,2.0,4.0,13844.000000,6908.0,27943.0,72.0,0,...,1.0,0.0,1.0,0.0,0.0,0.0,1.0,454276.0,0.0400,8.908018
3,13964.000000,8173.0,40.0,2.0,3.0,9553.000000,10844.0,27819.0,60.0,0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,335241.0,0.0961,9.544309
4,13284.000000,4223.0,31.0,2.0,1.0,9386.000000,37629.0,12741.0,72.0,1,...,1.0,1.0,0.0,0.0,1.0,0.0,1.0,519841.0,0.0841,9.494391
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,10852.571579,9092.0,58.0,0.0,0.0,5370.000000,43563.0,8311.0,72.0,4,...,1.0,1.0,0.0,0.0,0.0,1.0,0.0,310249.0,0.3481,9.292249
996,3279.000000,6356.0,58.0,1.0,3.0,9940.452632,18361.0,22563.0,12.0,0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,417316.0,0.0361,8.095599
997,15192.000000,8433.0,48.0,1.0,1.0,8581.000000,41335.0,16203.0,24.0,3,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,443556.0,0.1600,9.628590
998,9083.000000,7380.0,50.0,1.0,3.0,13491.000000,8933.0,10290.0,36.0,4,...,1.0,1.0,0.0,0.0,1.0,0.0,1.0,559504.0,0.0961,9.114270
999,13093.000000,2385.0,23.0,1.0,3.0,12436.000000,25816.0,35818.0,48.0,4,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,375769.0,0.1024,9.479909

In [138]:
X_train,X_test,Y_train,Y_test=train_test_split(
    X,Y,test_size=0.2,random_state=42
)

In [139]:
scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)

In [148]:
 #logistic regression 
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,precision_score,recall_score,confusion_matrix
model1=LogisticRegression(max_iter=5000)

model1.fit(X_train_scaled,Y_train)

Y_predict=model1.predict(X_test_scaled)

print("accuracy-",accuracy_score(Y_test,Y_predict))
print("recall-",recall_score(Y_test,Y_predict))
print("precison-",precision_score(Y_test,Y_predict))
print(confusion_matrix(Y_test,Y_predict))

accuracy- 0.86
recall- 0.7540983606557377
precison- 0.7796610169491526
[[126  13]
 [ 15  46]]

In [149]:
#KNN
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score,precision_score,recall_score,confusion_matrix
model2=KNeighborsClassifier(n_neighbors=7)

model2.fit(X_train_scaled,Y_train)

Y_predict=model2.predict(X_test_scaled)

print("accuracy-",accuracy_score(Y_test,Y_predict))
print("recall-",recall_score(Y_test,Y_predict))
print("precison-",precision_score(Y_test,Y_predict))
print(confusion_matrix(Y_test,Y_predict))

accuracy- 0.81
recall- 0.5573770491803278
precison- 0.7555555555555555
[[128  11]
 [ 27  34]]

In [150]:
#naive_bayes
#KNN
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score,precision_score,recall_score,confusion_matrix
model3=GaussianNB()
model3.fit(X_train_scaled,Y_train)

Y_predict=model3.predict(X_test_scaled)

print("accuracy-",accuracy_score(Y_test,Y_predict))
print("recall-",recall_score(Y_test,Y_predict))
print("precison-",precision_score(Y_test,Y_predict))
print(confusion_matrix(Y_test,Y_predict))

accuracy- 0.865
recall- 0.7540983606557377
precison- 0.7931034482758621
[[127  12]
 [ 15  46]]